when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        # Whether to auto-refresh proxies by default (https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#auto-refresh)
        auto_refresh_proxies: true
        global_state:
            - App\Story\GroupStory
        orm:
            auto_persist:         true
            reset:
                connections: [ default ]
                entity_managers: [ default ]
                mode: schema
when@test: *dev
